name: Deploy to AWS EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4        # was v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4  # was v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login \
          --username AWS \
          --password-stdin 688525135605.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build and push backend
        run: |
          docker build -t ai-rag-app:backend ./backend
          docker tag ai-rag-app:backend 688525135605.dkr.ecr.ap-south-1.amazonaws.com/ai-rag-app:backend
          docker push 688525135605.dkr.ecr.ap-south-1.amazonaws.com/ai-rag-app:backend

      - name: Build and push frontend
        run: |
          docker build -t ai-rag-app:frontend ./frontend
          docker tag ai-rag-app:frontend 688525135605.dkr.ecr.ap-south-1.amazonaws.com/ai-rag-app:frontend
          docker push 688525135605.dkr.ecr.ap-south-1.amazonaws.com/ai-rag-app:frontend

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            aws ecr get-login-password --region ap-south-1 | docker login \
            --username AWS \
            --password-stdin 688525135605.dkr.ecr.ap-south-1.amazonaws.com
            docker-compose -f docker-compose.prod.yml pull
            docker-compose -f docker-compose.prod.yml up -d